sudo: required

language: python

matrix:
    include:
    - python: '2.7'
    - python: '3.3'

before_install:
  - bash travis/install-redis.sh

install:
  - make install-ci

script:
  - make test lint
